name: BungeeAPI
version: 1.0
main: org.mooner.moonerbungeeapi.MoonerBungee
api-version: 1.18

commands:
  keyword:
    usage: "/keyword"
    aliases:
      - 키알
      - 키워드알림
      - zldkf
      - zldnjemdkffla